flotten/website/auth.py
from flask import Blueprint, render_template, flash, redirect, url_for
from website.models import User
from werkzeug.security import generate_password_hash, check_password_hash
from website import db
from flask_wtf import FlaskForm
# The biggest advantage of WTForms is that it contains rules for email and password validations
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Email
from flask_login import login_user, login_required, logout_user, current_user
from functools import wraps

auth = Blueprint("auth", __name__)


# define a decorator whereupon a function only gets triggered if the user is an admin
# and returns the user to the login page if he is not
def admin_required(f):
    @wraps(f)
    def wrap(*args, **kwargs):
        if current_user.is_admin:
            return f(*args, **kwargs)
        else:
            flash("You need to be an admin to view this page.", category="danger")
            return redirect(url_for('auth.login'))
    return wrap


# defines the login form
class LoginForm(FlaskForm):
    email = StringField(label="Email", validators=[DataRequired(), Email()])
    password = PasswordField(label="Password", validators=[DataRequired()])
    # remember field allows users to stay logged in after closing the browsers using a secure cookie
    remember = BooleanField(label="Remember Me")
    submit = SubmitField(label="Login")


# parameter methods shows which methods get accepted by the route
# handles the login-procedure
@auth.route("/", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():

        # create first admin if not yet created
        if not User.query.filter(User.email == 'admin@zug.at').first():
            db.session.commit()
            user = User(
                email='admin@zug.at',
                password=generate_password_hash("admin", method="sha256"),
                is_admin=True
            )
            db.session.add(user)
            db.session.commit()
            print("admin created!")

        # create first employee if not yet created
        if not User.query.filter(User.email == 'emp@zug.at').first():
            user = User(
                email='emp@zug.at',
                password=generate_password_hash("emp", method="sha256")
            )
            db.session.add(user)
            db.session.commit()
            print("employee created!")

        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                # the categories success and danger are categories of bootstrap
                flash(f"Willkommen zurück {user.email}!", category="success")
                login_user(user, remember=form.remember.data)
                return redirect(url_for("views.home"))
            else:
                flash("Passwort ist falsch, versuche es nochmal.", category="danger")
        else:
            flash("E-Mail existiert nicht.", category="danger")

    return render_template("login.html", form=form, user=current_user)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))

flotten/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
          crossorigin="anonymous">

    <link rel="stylesheet" href="static/css/styles.css">

    <title>Flotten-Informationssystem</title>
    {% block css %} {% endblock %}

</head>
<body>

<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #EFEDE4;">


    {% block leftnavbartext %} {% endblock %}

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav ms-auto px-4">
            {% if user.is_authenticated and user.is_admin %}
            <li class="nav-item px-2">
                <a class="nav-link" href="{{ url_for('views.home') }}">Dashboard</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link" href="{{ url_for('views.flotten') }}">Flottenverwaltung</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link" href="{{ url_for('views.wartungen') }}">Wartungensverwaltung</a>
            </li>
            <li class="nav-item px-2">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% elif user.is_authenticated %}
            <li class="nav-item px-2">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<!-- because the messages are defined here in base.html, messages can be flashed in any html file -->
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}

<!-- print out the message -->
<div class="alert alert-{{ category }} alter-dismissable fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert">
    </button>
</div>

{% endfor %} {% endif %} {% endwith %}
<br>
<div class="container">{% block content %} {% endblock %}</div>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous">
    </script>

</body>
<!--{% block script %} {% endblock %}-->
<br>
<br>
</html>

flotten/website/templates/emp-dashboard.html
{% extends "base.html" %}

{% block leftnavbartext %}
<h1>Mitarbeiter-Dashboard</h1>
{% endblock %}

{% block content %}

<h2>Meine Wartungen</h2>
<br>
<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Datum</th>
        <th scope="col">Start</th>
        <th scope="col">Ende</th>
        <th scope="col">Zug</th>
    </tr>
    </thead>
    <tbody>
    {% for wartung in wartungen %}
    {% if wartung.mitarbeiter == current_user.id %}
    <tr>
        <td>{{ wartung.datum }}</td>
        <td>{{ wartung.start.strftime("%H:%M") }}</td>
        <td>{{ wartung.ende.strftime("%H:%M") }}</td>
        <td>{{ wartung.train_maintenance }}</td>
    </tr>
    {% endif %}
    {% endfor %}
    </tbody>
</table>

<br>

<h2>Aktuelle Züge</h2>

<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Zugnummer</th>
        <th scope="col">Gewicht</th>
        <th scope="col">Spurweite</th>
        <th scope="col">Sitzanzahl</th>
        <th scope="col">Triebwagen</th>
        <th scope="col">Personenwaggon(s)</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for zug in zuege %}
    <tr>
        <td>{{ zug.nummer }}</td>

        {% set zug_gewicht = namespace(value=0) %}
        {% set zug_sitzanzahl = namespace(value=0) %}
        {% set zug_spurweite = namespace(value=0) %}
        {% set zug_triebwagen = namespace(value=0) %}

        {% for waggon in zug.waggons %}
        {% if waggon.__class__.__name__ == "Personenwaggon": %}
        {% set zug_gewicht.value = zug_gewicht.value + waggon.gewicht %}
        {% set zug_sitzanzahl.value = zug_sitzanzahl.value + waggon.sitzanzahl %}
        {% else %}
        {% set zug_triebwagen.value = waggon.fg_nummer %}
        {% set zug_spurweite.value = waggon.spurweite %}
        {% endif %}
        {% endfor %}

        <td>{{ zug_gewicht.value }}</td>
        <td>{{ zug_spurweite.value }}</td>
        <td>{{ zug_sitzanzahl.value }}</td>
        <td>{{ zug_triebwagen.value }}</td>
        <td>
            <select class="form-select" aria-label="Disabled select example" name="p_waggons" id="p_waggons" size="3"
                    multiple>
                {% for waggon in zug.waggons %}
                {% if waggon.__class__.__name__ == "Personenwaggon": %}
                <option disabled>{{ waggon.fg_nummer }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<br>

<h2>Aktuelle Waggons</h2>

<table class="table" id="emp-table">
    <thead class="table-light">
    <tr>
        <th scope="col">Fahrgestellnummer</th>
        <th scope="col">Typ</th>
        <th scope="col">Spurweite</th>
        <th scope="col">Sitzanzahl</th>
        <th scope="col">Max. Zugkraft</th>
        <th scope="col">Gewicht</th>
        <th scope="col">Teil eines Zuges</th>
    </tr>
    </thead>
    <tbody>
    {% for waggon in waggons %}
    <tr>
        <td>{{ waggon.fg_nummer }}</td>
        <td>{{ waggon.__class__.__name__ }}</td>
        <td>{{ waggon.spurweite }}</td>
        <td>{{ waggon.sitzanzahl }}</td>
        <td>{{ waggon.max_zugkraft }}</td>
        <td>{{ waggon.gewicht }}</td>
        {% if waggon.in_verwendung == True %}
        <td>Ja</td>
        {% else %}
        <td>Nein</td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>

<script>
    function colorTable() {
        var x = document.getElementById("emp-table").getElementsByTagName("td");
        for(let i = 0; i < x.length; i++) {
            if(x[i].innerText == "Nein") {
                for(let j = 6; j > -1; j--) {
                    console.log(x)
                    //x[i-j].style.backgroundColor = "rgb(239, 237, 228)";
                    x[i-j].style.backgroundColor = "rgb(255, 253, 250)";
                }
            }
        }
    }
    colorTable();
</script>

{% endblock %}

flotten/website/templates/flotten.html
{% extends "base.html" %}

{% block leftnavbartext %}
<h1>Flotte verwalten</h1>
{% endblock %}

{% block content %}

<h2>Aktuelle Züge</h2>

<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Zugnummer</th>
        <th scope="col">Gewicht</th>
        <th scope="col">Spurweite</th>
        <th scope="col">Sitzanzahl</th>
        <th scope="col">Triebwagen</th>
        <th scope="col">Personenwaggon(s)</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for zug in zuege %}
    <tr>
        <td>{{ zug.nummer }}</td>

        {% set zug_gewicht = namespace(value=0) %}
        {% set zug_sitzanzahl = namespace(value=0) %}
        {% set zug_spurweite = namespace(value=0) %}
        {% set zug_triebwagen = namespace(value=0) %}

        {% for waggon in zug.waggons %}
        {% if waggon.__class__.__name__ == "Personenwaggon": %}
        {% set zug_gewicht.value = zug_gewicht.value + waggon.gewicht %}
        {% set zug_sitzanzahl.value = zug_sitzanzahl.value + waggon.sitzanzahl %}
        {% else %}
        {% set zug_triebwagen.value = waggon.fg_nummer %}
        {% set zug_spurweite.value = waggon.spurweite %}
        {% endif %}
        {% endfor %}

        <td>{{ zug_gewicht.value }}</td>
        <td>{{ zug_spurweite.value }}</td>
        <td>{{ zug_sitzanzahl.value }}</td>
        <td>{{ zug_triebwagen.value }}</td>
        <td>
            <select class="form-select" aria-label="Disabled select example" name="p_waggons" id="p_waggons" size="3"
                    multiple>
                {% for waggon in zug.waggons %}
                {% if waggon.__class__.__name__ == "Personenwaggon": %}
                <option disabled>{{ waggon.fg_nummer }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </td>

        <td>
            <div class="btn-group">
                <button
                        type="button"
                        class="btn btn-sm btn-secondary dropdown-toggle"
                        data-bs-toggle="dropdown"
                ></button>
                <ul class="dropdown-menu">
                    <li>
                        <a href="/delete-zug/{{zug.id}}" class="dropdown-item">Auflösen</a>
                        <a href="/edit-zug/{{zug.id}}" class="dropdown-item">Bearbeiten</a>
                    </li>
                </ul>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<br>
<h2>Aktuelle Waggons</h2>
<form method="POST" action="">
    <table class="table" id="emp-table">
        <thead class="table-light">
        <tr>
            <th scope="col"></th>
            <th scope="col">Fahrgestellnummer</th>
            <th scope="col">Typ</th>
            <th scope="col">Spurweite</th>
            <th scope="col">Sitzanzahl</th>
            <th scope="col">Max. Zugkraft</th>
            <th scope="col">Gewicht</th>
            <th scope="col">Teil von Zug</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>

        {% for waggon in waggons %}
        <tr>
            <td>
                <input type="checkbox"
                       id="gewaehlt_fuer_zug"
                       name="gewaehlt_fuer_zug"
                       class="input-small"
                       value="{{ waggon.id }}">
            </td>
            <td>{{ waggon.fg_nummer }}</td>
            <td>{{ waggon.__class__.__name__ }}</td>
            <td>{{ waggon.spurweite }}</td>
            <td>{{ waggon.sitzanzahl }}</td>
            <td>{{ waggon.max_zugkraft }}</td>
            <td>{{ waggon.gewicht }}</td>
            {% if waggon.in_verwendung == True %}
            <td>Ja</td>
            {% else %}
            <td>Nein</td>
            {% endif %}
            <td>
                <div class="btn-group">
                    <button
                            type="button"
                            class="btn btn-sm btn-secondary dropdown-toggle"
                            data-bs-toggle="dropdown"
                    ></button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/delete-waggon/{{waggon.id}}" class="dropdown-item">Löschen</a>
                            <a href="/edit-waggon/{{waggon.id}}" class="dropdown-item">Bearbeiten</a>
                        </li>
                    </ul>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <br>
    <label for="zugnummer_manuell">Zugart (optional, sonst zufällig):</label>
    <select
            id="zugnummer_manuell"
            name="zugnummer_manuell"
            class="input-small">
        <option value="none" selected disabled hidden>Auswählen</option>
        <option value="RJ">RJ</option>
        <option value="WB">WB</option>
        <option value="S">S</option>
        <option value="NJ">NJ</option>
        <option value="ICE">ICE</option>
        <option value="IC">IC</option>
        <option value="RJX">RJX</option>
    </select>

    <button type="submit" name="submit_zug" class="btn btn-secondary btn-sm" value="submit_zug">Zug mit ausgewählten
        Waggons erstellen
    </button>
</form>

<br>
<br>

<h5 class="mb-3">Triebwagen erstellen:</h5>
<form method="POST" action="" class="form-inline">

    <label for="t_spurweite">Spurweite:</label>
    <select
            id="t_spurweite"
            name="t_spurweite"
            class="input-small">
        <option value="1435">1435</option>
        <option value="1067">1067</option>
    </select>

    <label for="max_zugkraft">Maximale Zugkraft:</label>
    <input type="text"
           id="max_zugkraft"
           name="max_zugkraft"
           class="input-small"
           size="10"
           placeholder="in Tonnen"
           value="{{ max_zugkraft }}">

    <button type="submit" name="submit_twagen" class="btn btn-secondary btn-sm" value="submit_twagen">Erstellen</button>
    <br>

</form>

<br>
<h5 class="mb-3">Personenwaggon erstellen:</h5>
<form method="POST" action="" class="form-inline">

    <label for="p_spurweite">Spurweite:</label>
    <select
            id="p_spurweite"
            name="p_spurweite"
            class="input-small">
        <option value="1435">1435</option>
        <option value="1067">1067</option>
    </select>

    <label for="sitzanzahl">Sitzanzahl:</label>
    <input type="text"
           id="sitzanzahl"
           name="sitzanzahl"
           class="input-small"
           size="10"
           value="{{ sitzanzahl }}">

    <label for="gewicht">Gewicht:</label>
    <input type="text"
           id="gewicht"
           name="gewicht"
           class="input-small"
           size="10"
           placeholder="in Tonnen"
           value="{{ gewicht }}">

    <button type="submit" name="submit_pwagen" class="btn btn-secondary btn-sm" value="submit_pwagen">Erstellen</button>
    <br>

</form>

<script>
    function colorTable() {
        var x = document.getElementById("emp-table").getElementsByTagName("td");
        for(let i = 0; i < x.length; i++) {
            if(x[i].innerText == "Nein") {
                for(let j = 7; j > -1; j--) {
                    console.log(x)
                    //x[i-j].style.backgroundColor = "rgb(239, 237, 228)";
                    // x[i-j].style.backgroundColor = "rgb(255, 253, 250)";
                    x[i-j].style.backgroundColor = "#FDF5E6";
                }
            }
        }
    }
    colorTable();



</script>

{% endblock %}

flotten/website/templates/home.html
{% extends "base.html" %}

{% block leftnavbartext %}
<h1>Administrator-Dashboard</h1>
{% endblock %}

{% block content %}

<h2>Aktuelle Züge</h2>

<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Zugnummer</th>
        <th scope="col">Gewicht</th>
        <th scope="col">Spurweite</th>
        <th scope="col">Sitzanzahl</th>
        <th scope="col">Triebwagen</th>
        <th scope="col">Personenwaggon(s)</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    {% for zug in zuege %}
    <tr>
        <td>{{ zug.nummer }}</td>

        {% set zug_gewicht = namespace(value=0) %}
        {% set zug_sitzanzahl = namespace(value=0) %}
        {% set zug_spurweite = namespace(value=0) %}
        {% set zug_triebwagen = namespace(value=0) %}

        {% for waggon in zug.waggons %}
        {% if waggon.__class__.__name__ == "Personenwaggon": %}
        {% set zug_gewicht.value = zug_gewicht.value + waggon.gewicht %}
        {% set zug_sitzanzahl.value = zug_sitzanzahl.value + waggon.sitzanzahl %}
        {% else %}
        {% set zug_triebwagen.value = waggon.fg_nummer %}
        {% set zug_spurweite.value = waggon.spurweite %}
        {% endif %}
        {% endfor %}

        <td>{{ zug_gewicht.value }}</td>
        <td>{{ zug_spurweite.value }}</td>
        <td>{{ zug_sitzanzahl.value }}</td>
        <td>{{ zug_triebwagen.value }}</td>
        <td>
            <select class="form-select" aria-label="Disabled select example" name="p_waggons" id="p_waggons" size="3"
                    multiple>
                {% for waggon in zug.waggons %}
                {% if waggon.__class__.__name__ == "Personenwaggon": %}
                <option disabled>{{ waggon.fg_nummer }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<br>

<h2>Aktuelle Waggons</h2>

<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Fahrgestellnummer</th>
        <th scope="col">Typ</th>
        <th scope="col">Spurweite</th>
        <th scope="col">Sitzanzahl</th>
        <th scope="col">Max. Zugkraft</th>
        <th scope="col">Gewicht</th>
        <th scope="col">Teil eines Zuges</th>
    </tr>
    </thead>
    <tbody>
    {% for waggon in waggons %}
    <tr>
        <td>{{ waggon.fg_nummer }}</td>
        <td>{{ waggon.__class__.__name__ }}</td>
        <td>{{ waggon.spurweite }}</td>
        <td>{{ waggon.sitzanzahl }}</td>
        <td>{{ waggon.max_zugkraft }}</td>
        <td>{{ waggon.gewicht }}</td>
        {% if waggon.in_verwendung == True %}
        <td>Ja</td>
        {% else %}
        <td>Nein</td>
        {% endif %}
    </tr>
    {% endfor %}
    </tbody>
</table>

<br>
<h2>Aktuelle Wartungen</h2>
<br>
<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Datum</th>
        <th scope="col">Start</th>
        <th scope="col">Ende</th>
        <th scope="col">Zug</th>
        <th scope="col">Mitarbeiter</th>
    </tr>
    </thead>
    <tbody>
    {% for wartung in wartungen %}
    <tr>
        <td>{{ wartung.datum }}</td>
        <td>{{ wartung.start.strftime("%H:%M") }}</td>
        <td>{{ wartung.ende.strftime("%H:%M") }}</td>
        <td>{{ wartung.train_maintenance }}</td>
        <td>{{ wartung.maintenance }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<br>
<h2>Aktuelle Mitarbeiter</h2>
<br>

<table class="table">
    <thead class="table-light">
    <tr>
        <th scope="col">Name</th>
        <th scope="col">E-Mail</th>
        <th scope="col">Eingeteilte Wartungen</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
    <tr>
        <td>{{ user.email.partition("@")[0] }}</td>
        <td>{{ user.email }}</td>
        {% if user.is_admin %}
        <td>Keine, weil Admin</td>
        {% else %}
        <td>
            <select class="form-select" aria-label="Disabled select example" name="user_wartungen" id="user_wartungen"
                    size="3"
                    multiple>
                {% for wartung in user.wartungen %}
                <option disabled>{{ user.wartungen[loop.index0]|string + ", " + wartung.train_maintenance|string }}</option>
                {% endfor %}
            </select>
        </td>
        {% endif %}

         <td>
                <div class="btn-group">
                    <button
                            type="button"
                            class="btn btn-sm btn-secondary dropdown-toggle"
                            data-bs-toggle="dropdown"
                    ></button>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="/delete-user/{{user.id}}" class="dropdown-item">Löschen</a>
                            <a href="/edit-user/{{user.id}}" class="dropdown-item">Bearbeiten</a>
                        </li>
                    </ul>
                </div>
            </td>

    </tr>
    {% endfor %}
    </tbody>
</table>

<br>
<form method="POST" action="" class="form-inline">

    <label for="email">E-Mail:</label>
    <input type="text"
           id="email"
           name="email"
           class="input-small"
           placeholder="name@zug.at"
           value="{{ email }}">

    <label for="passwort">Passwort:</label>
    <input type="text"
           id="passwort"
           name="passwort"
           class="input-small"
           size="10"
           maxlength="4"
           value="{{ passwort }}">

        <label for="is_admin">Admin:</label>
        <input type="checkbox" id="is_admin" name="is_admin" class="input-small">

    <button type="submit" name="submit_mitarbeiter" class="btn btn-secondary btn-sm" value="submit_mitarbeiter">
        Erstellen
    </button>
    <br>

</form>

{% endblock %}

flotten/website/templates/login.html
{% extends "base.html" %}

{% block leftnavbartext %}
<h1>Flotten-Informationssystem</h1>
{% endblock %}

{% block content %}

<div class="content-section">
    <!--    when action is empty that means that the form is posted to the same route we are on-->
    <form method="POST" action="">
        <!--    the hidden_tag adds a csrf (cross site request forgery) token; needed for protection stuff-->
        {{ form.hidden_tag() }}
        <fieldset class="form-group mt-4 login-comp">
            <legend class="border-bottom mb-4">Login</legend>
            <div class="form-group">
            <!--    using the fields from the form which got passed in-->
                {{ form.email.label(class="form-control-label") }}
                                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check mt-3">
              {{ form.remember(class="form-check-input") }}
              {{ form.remember.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group login-comp">
            {{ form.submit(class="btn btn-secondary btn-custom mt-3") }}
        </div>
    </form>
</div>

{% endblock %}

flotten/website/templates/user-edit.html
{% extends "base.html" %}

{% block leftnavbartext %}
<h1>User bearbeiten</h1>
{% endblock %}

{% block content %}

<form method="POST" action="" class="form-inline">

    <label for="user_name">Name:</label>
    <input type="text"
           id="user_name"
           name="user_name"
           class="input-small"
           value="{{ user_to_edit.email.partition('@')[0] }}"
    disabled>

    <label for="user_email">E-Mail:</label>
    <input type="email"
           id="user_email"
           name="user_email"
           class="input-small"
           value="{{ user_to_edit.email }}">

    <label for="user_admin_rights">Admin-Rechte:</label>
    <input type="checkbox" id="user_admin_rights" name="user_admin_rights" class="input-small">

    <button type="submit" name="submit_user" class="btn btn-secondary btn-sm" value="submit_user">Speichern
    </button>
    <br>

</form>


{% endblock %}